spring:
  profiles:
    # 启用环境配置文件
    active: development
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 120.26.4.86
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: DDim4RJO
