server:
  port: 8000

application:
  message: 这是开发环境

logging:
  path: D:\\idea_workspace\\zxott
  level:
    root: INFO
    com.zhexinit.taobaocrbt: debug

spring:
  datasource:
    xingbookuser:
      jdbc-url: jdbc:mysql://120.26.4.86:3306/xingbook_user?useUnicode=true&characterEncoding=utf-8
      username: root
      password: tryme
    xingbook:
      jdbc-url: jdbc:mysql://120.26.4.86:3306/xingbook?useUnicode=true&characterEncoding=utf-8
      username: root
      password: tryme
